language: objective-c

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

script:
  - xctool test -project Source/Swizzler.xcworkspace -scheme Swizzler -sdk macosx10.10
  - xctool test -workspace Swizzler.xcworkspace -scheme Swizzler -sdk iphonesimulator7.1 -destination "platform=iOS Simulator,name=iPhone 5,OS=7.1"
  - xctool test -workspace Swizzler.xcworkspace -scheme Swizzler -sdk iphonesimulator7.1 -destination "platform=iOS Simulator,name=iPhone 5s,OS=7.1"
  - xctool test -workspace Swizzler.xcworkspace -scheme Swizzler -sdk iphonesimulator8.1 -destination "platform=iOS Simulator,name=iPhone 6,OS=8.1"
  - xctool test -workspace Swizzler.xcworkspace -scheme Swizzler -sdk iphonesimulator8.1 -destination "platform=iOS Simulator,name=iPhone 6 plus,OS=8.1"

notifications:
  email:
    - v.andersson@me.com